spring:
  application:
    name: 
  datasource:
    url: 
    username: 
    password:
  kafka:
    bootstrap-servers: 
    consumer:
      group-id: 
    listener:
      concurrency: 4

server:
  port: 

logging:
  level: 
  file: 
